### ISSUE TITLE
Randomly pauses on playback of cached or streamed files

### ISSUE THREAD

**Issue by nate2014jatc** [ultrasonic/ultrasonic#228] opened 2018-08-22 15:13 UTC
## Problem description

As the title suggests, I'm here for a playback issue. Ultrasonic will frequently interrupt my music playback by outright pausing the song for no apparent reason. 

### Steps to reproduce

1). Play song
2). Get interrupted. 

## System information

 * **Ultrasonic version**: *2.6.0*
 * **Android version**: *8.1.0*
 * **Device info**: *Google/Huawei Nexus 6P*

**Comment by Tapchicoma** [comment] 2018-08-23 18:28
@nate2014jatc do you have stable network while you are playing songs? 

It may happen that Ultrasonic doesn't have enought time/bandwidth to download currently playing song.

**Comment by nate2014jatc** [comment] 2018-09-07 17:53
I could have sworn I replied to this through email.

The error happens even when I'm working with offline media that's already been cached

**Comment by schniepp** [comment] 2018-10-07 14:15
I am experiencing a similar issue (playback goes to pause after about 1 minute), and I am wondering if it is related. In my case it **only** happens when I listen via a Bluetooth connected device. The problem does not occur at all when I listen via built-in speaker or wired (analog) headphones.

For my case, I did quite a bit of testing, and depending on your answer, I will either provide all my details here or file a new bug.

**Comment by gogigopuduh** [comment] 2018-12-06 13:56
I have exactly the same problem. it only happens connected through bluetooh, I have 3 Android devices (kitkat 4.4, marshmellow 6.0, oreo, 8.0) and in all cases it happens connected to the bluetooth speakers. If I use web playback I have no problems. subsonic is installed in a rasberry pi with jessie debian raspbian.


What tests can I perform to help find the bug?
Thank you

**Comment by pszabo75** [comment] 2019-01-30 22:40
Happens to me (and always happened since I use Ultrasonic) with wired and wireless headsets too. I was wondering if this might have been caused by some Android power saving feature, that breaks applications running in the background. I turned off battery optimization for Ultrasonic without any luck. I don't really find anything else in Pie settings that seems to be related.

**Comment by aminomaboul** [comment] 2019-05-25 14:50
For me. This happend when android put the app in sleep, when it's in the background.
I'm on android 9.0. Go to device care => batterie  and deactivate the option frol there.

**Comment by michaelcadilhac** [comment] 2020-05-24 21:56
Same here, headset, streaming or cached. It's always been the case. When I get fed up, I listen to the cached files with n7player.  The app is set as "exception" for battery management, so I don't think it's that.

H3113 on Android 9.

**Comment by ogarcia** [comment] 2020-11-06 17:45
This issue could be related with bluetooth devices now fixed. Close for now.

**Closed as completed by ogarcia** 2020-11-06 17:45 UTC
Labels: bug, need more info

**Comment by michaelcadilhac** [comment] 2020-11-06 18:32
FWIW, I was not using Bluetooth.  I'll give it a try soon.
