### ISSUE TITLE
Apostrophe character breaks play in offline mode

### ISSUE THREAD

**Issue by ogarcia** [ultrasonic/ultrasonic#248] opened 2019-03-19 13:02 UTC
## Problem description

If you download a song with an apostrophe in its name and try to play it in offline mode, you cannot. It appears fuzzy in the list (see screenshot).

![screenshot_2019-03-19_13-32-01](https://user-images.githubusercontent.com/572924/54606220-7a843c80-4a4b-11e9-9368-b13bec7cb002.jpg)

### Steps to reproduce

1. Download a song with apostrophe in its name like one of these:
- https://musicbrainz.org/recording/2b4c50b4-4aa9-4387-9b18-f17d04410ef7
- https://musicbrainz.org/recording/960d358d-b00f-48da-90b8-4e3643a29074
2. Go to offline mode.
3. Try to play it.

There is a sample file free of rights. It's _The Nutcracker Suite - Act I, No.4. Russian Dance_ but it have the tags modified to reproduce the bug.

[The Nutcracker Suite - Act I, No.4. Russian Dance.zip](https://github.com/ultrasonic/ultrasonic/files/2983385/The.Nutcracker.Suite.-.Act.I.No.4.Russian.Dance.zip)

**Comment by Tapchicoma** [comment] 2019-03-19 20:07
Is it happens only in offline mode? :thinking:

**Comment by ogarcia** [comment] 2019-03-20 07:38
Yes. Is a strange behaviour. I think that the problem is that in online mode the name is picked from api and this works well, but in offline mode the name is picked from tag and fails with some characters.

**Comment by nitehu** [comment] 2020-09-27 12:58
Apostrophes work now. I've checked multiple files (at least 30)

![Screenshot 2020-09-27 144800](https://user-images.githubusercontent.com/55684536/94365364-9fda1800-00d0-11eb-8d28-6c98886ababd.jpg)

I can only guess
- the problem was in `MediaMetadataRetriever` and google fixed it
- the characters on your screen seem to be a result of an encoding error (e.g. unicode was expected but the string was in UTF-8). Maybe that character wasn't an apostrophe, and was encoded wrongly.

@ogarcia can you find a file with which this can be reproduced?

**Comment by ogarcia** [comment] 2020-10-04 14:38
@nitehu sorry for delay. I send you a link vía Gitter :wink:

**Comment by nitehu** [comment] 2020-10-04 17:33
Yep, checked it and thats not an apostrophe... just an apostrophe shaped thingy... I hate UTF8...
It Ain’t Over ’til It’s Over '’'’'’ <- not sure if it can be seen with this font size, I've put them beside real apostrophes.
Anyways, as all tagging software can recognise them, I guess Ultrasonic should handle them (and other international characters) as well. I'll check if a simple conversion to UTF-8 will solve it, or there is another problem.

**Comment by ogarcia** [comment] 2020-10-04 17:49
These variation of apostrophe is used by default in [musicbrainz.org](https://musicbrainz.org/). If you use [beets](http://beets.io/) for tagging all apostrophes will be equal to these.

**Comment by nitehu** [comment] 2020-10-06 18:21
Okay so I naively thought this is an easy fix, boy was I wrong... Just look at this:

![Screenshot 2020-10-06 201137](https://user-images.githubusercontent.com/55684536/95243034-5300ea80-0810-11eb-8e7e-38df2031fb70.jpg)

So, these are unicode characters in the ID3 tags, read up by the Android `MediaMetadataRetriever` - only it sometimes makes a mistake, like if somebody hated Lenny Kravitz, it is really allergic to the `'til` characters after each other. Actually, between the `'` and the `til` there may be any characters, it still fails. If there is no til, it just works.

Tested this with Flac, that has the same problem, however Flac doesn't store the string in UTF-16 like the ID3, it uses UTF-8.

It's really puzzling, I have no clue why this happens. Checked the code of the `MediaMetadataRetriever`, but that has some native functions I can't see into.

Currently the best solution I can think of is to use a custom metadata reader library to solve this.

**Comment by Tapchicoma** [comment] 2020-10-06 18:28
Probably worth considering migration to ExoPlayer, especially after library authors added experimental power-efficient playback mode in latest release.

**Comment by nitehu** [comment] 2020-10-07 06:46
According to the ExoPlayer guys, "Due to SDK API limitations, ExoPlayer’s audio offload mode is only available on devices running Android 10 and above." So I guess this won't be viable in the near future.

Actually, I'm more inclined to add `replace("â€™","'")` as a workaround, and close back this Pandora's box at least until someone finds another character combination that fails (or when there is a permanent fix)

**Comment by ogarcia** [comment] 2020-10-10 09:40
Seems that is a bug in `MediaMetadataRetriever`, but open it to Google guys, we'll lucky if they fix it in next ten years

**Comment by tzugen** [comment] 2022-06-18 20:47
Is this still the case with the new beta?

**Comment by ogarcia** [comment] 2022-06-19 08:16
@tzugen Yes :disappointed:

**Comment by tzugen** [comment] 2022-07-08 09:50
We are moving to Gitlab. Please continue the discussion there: https://gitlab.com/ultrasonic/ultrasonic/-/issues/248

**Closed as completed by tzugen** 2022-07-08 09:50 UTC
Labels: bug
