### ISSUE TITLE
FR: Have a way to go up from Album to Artist Album list

### ISSUE THREAD

**Issue by weendigo** [ultrasonic/ultrasonic#165] opened 2018-02-13 14:15 UTC
## Problem description

Sometimes I have an issue that I land on album page with no means to go level up on the artist screen. It is possible using back button if you get there from Artist view. However, when you land there from search or Now Playing, the back button takes you correctly back and not one level up.

An option to go to artist's album screen without having to go through Media Library or Search would be very welcome.

### Steps to reproduce

1. Have some songs in your Now playing queue.
2. From the song context menu select Show Album
3. You land on Album screen
4. Now there's no direct way to go up to the artist's album list.

## System information

 * **Ultrasonic version**: 2.2.2
 * **Android version**: 7.0
 * **Device info**: Honor 8

**Comment by tzugen** [comment] 2021-05-28 12:56
Is this still reproducable?

**Comment by fkrivsky** [comment] 2021-05-28 14:07
Yes, the app behaves the same. The back arrow in the top left corner leads back to Now playing and not up in the library.

**Comment by tzugen** [comment] 2021-12-07 12:25
Best IMO would be to add a Show Artist into the context menu, that takes you straight to the artist. Interferring with the back behaviour would be against Android design standards

**Comment by ogarcia** [comment] 2022-07-06 10:23
We are migrating Ultrasonic development from GitHub to GitLab. To make the migration as clean as possible we are going to close this issue. If you are still interested in it, please open it again in [GitLab](https://gitlab.com/ultrasonic/ultrasonic/issues/new) from **July 11**.

WARNING: It is important that you don't do it immediately and wait until July 11 because what we [currently have in GitLab](https://gitlab.com/ultrasonic/ultrasonic/-/issues) [is a test](https://gitlab.com/ultrasonic/ultrasonic/-/issues/770) that we will delete.

Thank you very much for your understanding.

**Closed as completed by ogarcia** 2022-07-06 10:23 UTC
Labels: feature request, good first issue
