### ISSUE TITLE
I would like to see some real error messages displayed.

### ISSUE THREAD

**Issue by wagnered** [ultrasonic/ultrasonic#124] opened 2018-01-04 07:40 UTC
For example, Ampache doesn't implement the chat function in it's Subsonic API. It would be nice to not see "A network error has  occurred." When it is not a network error.

For example If Ampache's Podcast feature is not enabled, the Subsonic API issues an error response of "User is not authorized. "  The response includes both number and the message, so the Ultrasonic client should be able to display it, instead of "A network error has occurred....".

Ampache, being a "Third-Party" Subsonic emulator, should be able to issue error or other types of messages tailored to it's capabilities.

Thanks,

**Comment by ogarcia** [comment] 2018-01-04 07:46
Duplicate of #121

**Closed as completed by ogarcia** 2018-01-04 07:46 UTC
Labels: duplicate
