### ISSUE TITLE
Ultrasonic Android on Madsonic Server

### ISSUE THREAD

**Issue by sergiocos** [ultrasonic/ultrasonic#129] opened 2018-01-11 14:56 UTC
Hi! I'm using an older version of Madsonic server, latest free, without activation (MADSONIC 5.1.5260.20150831.0820) and after your latest update (latest two updates, actually) your android client can't connect to server. (A network error ocurred. Please check the server address or try again.) Happens on any device using Ultrasonic.
Thank you for all your work!

**Comment by ogarcia** [comment] 2018-01-11 20:31
@sergiocos If you see the logs into your server you will see the http requests. If you make same requests with **curl** you will obtain server responses.

Can you paste here the requests and responses?

**Comment by wannabe2g** [comment] 2018-01-18 01:09
I have the exact same issue.  I am using https and have a FW rule to punch through.  There are no events in the madsonic logs.  This seems to be since the last couple of updates

**Comment by ogarcia** [comment] 2018-01-18 09:35
@wannabe2g are you using https with a self-signed certificate? In this case you must check the self-signed option in server section of Ultrasonic config.

**Comment by sergiocos** [comment] 2018-01-18 11:14
I don't know much about debugging, so I can share the server build that I'm using (madsonic 5.1.5), so you can take a look, you have the time. Sorry that I can't be more helpful. link: https://www.dropbox.com/s/1yr1d8u0ps48vlj/20150831_madsonic-5.1.5260-setup-x64.zip?dl=0

**Comment by ogarcia** [comment] 2018-01-18 11:19
@sergiocos please test with the following version: https://f-droid.org/repo/org.moire.ultrasonic_58.apk

**Comment by sergiocos** [comment] 2018-01-18 11:22
Thank you. Works great now!

**Comment by wannabe2g** [comment] 2018-01-18 13:09
@ogarcia The SSl cert that is used is the default one that came with Madsonic version.  I have not update it.  I tried to download the apk above and it fails with the message that it is corrupted and cannot be installed.  The self signed cert is checked.

@sergiocos , all I did was to download the apk using the link (this is on Moto Droid Ultra. Did you do any other step(s) to get this to install?

**Comment by sergiocos** [comment] 2018-01-18 13:14
Nothing, just allowing install from unknown sources on my LG v20

**Comment by ogarcia** [comment] 2018-01-18 13:50
@wannabe2g I think that your problem is related with server certificate. Maybe it's expired.

Can you try to serve your Madsonic via http to discard certificate problems?

**Comment by ogarcia** [comment] 2018-01-23 12:55
@wannabe2g @sergiocos we updated the APP to version 2.2.0 with several improvements. Please upgrade it from Play Store or download by hand from https://github.com/ultrasonic/ultrasonic/releases/download/2.2.0/ultrasonic-2.2.0.apk and tell us if the issue is solved.

**Comment by sergiocos** [comment] 2018-01-23 15:45
Sadly, I got again 'Connection failure' (A network error ocurred. Please check the server address or try again.) I checked support for LDAP users, same behaviour.

**Comment by ogarcia** [comment] 2018-01-23 15:49
@sergiocos Would you open a private chat with me in https://gitter.im/ultrasonic/ultrasonic and provide a test user in your server to I can debug the issue?

**Comment by ogarcia** [comment] 2018-01-23 16:29
Ok. Error found. Is caused because Madsonic returns a non standard API level.
```
{"subsonic-response": {
  "status": "ok",
  "xmlns": "http://madsonic.org/restapi",
  "type": "madsonic",
  "version": "1.10.5"
}}
```

@Tapchicoma Here we have two posible solutions:
1. Declare Ultrasonic incompatible with Madsonic 5.1.*
2. Add a `"1.10.5" -> return V1_10_2 // Madsonic Server 5.1` in `SubsonicAPIVersions` class into `fromApiVersion` function (PR #145)
3. Other idea that you could have.

**Comment by Tapchicoma** [comment] 2018-01-23 20:08
Fix available on develop branch, will be in next release.

**Closed as completed by Tapchicoma** 2018-01-23 20:08 UTC
Labels: bug

**Comment by Tapchicoma** [comment] 2018-01-23 21:01
Released in version `2.2.1`

**Comment by ogarcia** [comment] 2018-01-23 21:16
Published version `2.2.1`.
@sergiocos can be downloaded from [here](https://github.com/ultrasonic/ultrasonic/releases/download/2.2.1/ultrasonic-2.2.1.apk).

**Comment by sergiocos** [comment] 2018-01-24 06:55
Thank you!

**Comment by sergiocos** [comment] 2018-02-03 10:55
There are still some issues. Some areas of Ultrasonic works great (Recently Added or Played, Search, Random etc.), there are still areas that throws the error mentioned above (A network error ocurred. Please check the server address or try again.) I get that error when trying to acces Playlists area or Media Library.

**Comment by ogarcia** [comment] 2018-02-03 13:15
@sergiocos This is caused by a bad implementation of Subsonic API by Madsonic. For example, when you ask for Media Library the first request to server is like the following `curl`.
```
curl 'http://example.com:4040/rest/getMusicFolders.view?u=USER&c=UltraSonic%2520for%2520Android&f=json&v=1.7.0&p=enc:ENCPASS'
```

A good response for the above request is some like this.
```
{
  "subsonic-response": {
    "musicFolders": {
      "musicFolder": [
        {
          "id": "1b2a156d-56da-4705-8f1c-fb68752cbb91",
          "name": "Music"
        }
      ]
    },
    "status": "ok",
    "version": "1.8.0"
  }
}
```

But Madsonic response is like this.
```
{
  "subsonic-response": {
    "status": "ok",
    "xmlns": "http://madsonic.org/restapi",
    "musicFolders": {
      "musicFolder": {
        "id": 0,
        "name": "Music"
      }
    },
    "type": "madsonic",
    "version": "1.10.5"
  }
}
```

The point is in `musicFolder`, that must return the `id` and `name` into an array `[ ]` but it returns directly.

They have a similar issue with `getIndexes.view` where the `artist` must be always an array `[ ]` but it returns directly if only there is an artist in the index, as you can see in the following sample.
```
{
  "subsonic-response": {
    "status": "ok",
    "indexes": {
      "index": [
        {
          "name": "A",
          "artist": [
            {
              "id": 62,
              "name": "Aerosmith"
            },
            {
              "id": 61,
              "name": "Arcade Fire"
            }
          ]
        },
        {
          "name": "W",
          "artist": {
            "id": 1,
            "name": "White Lies"
          }
        }
      ],
      "lastModified": 1517663406000,
      "ignoredArticles": "The El La Los Las Le Les"
    },
    "xmlns": "http://madsonic.org/restapi",
    "type": "madsonic",
    "version": "1.10.5"
  }
}
```

The artist in `A` index are returned good, but the artist in `W` not.

This is a Madsonic bug that we cannot fix. You can try file a bug into [Madsonic forum](http://forum.madsonic.org/viewforum.php?f=30) with this info, but version 5 is an old version and I don't know if they will make a patch for this.

**Comment by nitehu** [comment] 2020-09-20 15:14
Ok I've just found out that Ampache does this too, just in the response for "getChatMessages" (or maybe for other requests too, I have too many songs/albums/artists to test...)

The best solution would be to search for a json serializer that supports this, for maximum compatibility on Ultrasonic's end.
Also, [fixing this may be a one-liner](https://stackoverflow.com/questions/17003823/make-jackson-interpret-single-json-object-as-array-with-one-element).
