### ISSUE TITLE
Offline Mode weird loading + timeout thingy

### ISSUE THREAD

**Issue by davidgfnet** [ultrasonic/ultrasonic#223] opened 2018-08-09 10:32 UTC
So in offline mode, some of my albums will do something weird when I try to open them. It will show loading ... as if it was still online mode and was trying to get from the http endpoint and at some point it will give up and show the album as expected.

Video: https://transfer.sh/sY81i/ultrasonic_bug.mp4
I'm in offline mode all the time during this video.

**Comment by Tapchicoma** [comment] 2018-08-17 08:35
Current implementation of offline mode is not reliable :disappointed:

**Comment by nitehu** [comment] 2020-10-07 19:20
Unfortunately the Video has gone in the meantime, so a more detailed description of the bug and how to reproduce it would be needed...

**Comment by tzugen** [comment] 2021-05-28 12:52
Closing because can't reproduce. 
You are welcome to reopen if you still expirience this.

**Closed as completed by tzugen** 2021-05-28 12:52 UTC
Labels: bug, need more info
