### ISSUE TITLE
Notification is stuck in the status bar

### ISSUE THREAD

**Issue by nitehu** [ultrasonic/ultrasonic#262] opened 2020-01-12 16:24 UTC
## Problem description
The notification can be stuck on the status bar. It won't disappear on the press of the close (x) button (but playback stops normally).

### Steps to reproduce
1. Start playback of a song
2. Open notification, press (x). Playback stops and the notification disappears normally
3. Start the playback again in Ultrasonic. Notification reappears
4. Open notification, press (x). Playback stops, but the notification remains!

The stuck notification can be closed again when the next track is selected.

## System information

 * **Ultrasonic version**: 2.5.0 (also present in latest master and develop)
 * **Android version**: 9
 * **Device info**: Samsung Galaxy Note 9, also in Android Emulator

**Comment by mjanssens** [comment] 2020-01-16 11:04
This seems like a duplicate of #103 
Issue is still present on my phone, however selecting next track doesn't fix it.

**Comment by nitehu** [comment] 2020-01-16 19:55
Oh I see, this problem is old... I can 100% reproduce it currently in Android Studio (with latest Ampache, not sure if that matters). I'll make some debugging and see if I can figure something out.

**Comment by nitehu** [comment] 2020-01-16 21:02
Yep the problem seems to be in DownloadServiceImpl.setPlayerState. It can create a new notification when the service is not in the foreground. stopForeground won't remove this new notification.
I'll create a patch for this when I have more time.

**Closed as completed** 2020-03-23 16:13 UTC
