### ISSUE TITLE
Error using Ampache server and Ultrasonic

### ISSUE THREAD

**Issue by prschopf** [ultrasonic/ultrasonic#125] opened 2018-01-05 22:35 UTC
## Problem description

When I choose "song/artist" or "songs/favorites" or "albums/favorites" or "videos/videos" I get an error, something like that: "There was a network error. Check server url or try it later". Other options are working fine.

### Steps to reproduce

Using Ampache server, Ultrasonic app and Nexus 4 cellphone.

## System information

 * **Ultrasonic version**: 2.1.0
 * **Android version**: 7.1.2 (Lineage 14)
 * **Device info**: Google LG Nexus 4
 * **Ampache server version**: 3.8.4 (tried with 3.8.3 too, same error) - Using httpS

**Comment by craftyguy** [comment] 2018-01-06 06:40
I'm also seeing this too, with a similar setup.

**Comment by ogarcia** [comment] 2018-01-06 10:16
Duplicate of #109 and related with https://github.com/ampache/ampache/issues/1651 already fixed in Ampache.

Please see  this commit https://github.com/ampache/ampache/commit/79105a8cd6074a2bb32def2018f06ef2191a1138

You must wait for a new release of Ampache or use master.

**Closed as completed** 2018-01-06 10:17 UTC
Labels: duplicate, not our bug
