### ISSUE TITLE
Cannot use sdcard for cache location

### ISSUE THREAD

**Issue by topas-rec** [ultrasonic/ultrasonic#231] opened 2018-09-17 10:20 UTC
## Problem description

I cannot set the cache location to sdcard. I want to use my sdcard for caching music files.
(If this usage is wrong please help me set up the sdcard path correctly)

### Steps to reproduce

In the settings for cache location enter "/storage/{sdcard identification numer}/Music" and press Ok.
ultrasonic says "invalid location" and sets back the default cache location.

## System information

 * **Ultrasonic version**: 2.6.0
 * **Android version**: 7.1 (lineageOS)
 * **Device info**: LG G4 (H815)

## Additional notes

Might have to do with permissions. So perhaps related to #79 and might be solved with #98.

**Comment by ogarcia** [comment] 2018-09-17 10:40
Duplicate of #98

**Closed as completed by ogarcia** 2018-09-17 10:40 UTC
Labels: duplicate

**Comment by topas-rec** [comment] 2018-09-17 11:50
Is there a workaround or simply not possible at the moment?

**Comment by delightfuldude** [comment] 2020-05-26 13:54
Does this work now? How to save to SD card?
